### ISSUE TITLE
Add CI-jobs for checking ci configs are working fine

### ISSUE THREAD

**Issue by zemuvier** [esikachev/my-dev-ci-config#9]
At least we need bashcheck to check syntax and pep8

**Comment by esikachev** [comment]
good point)

**Comment by zemuvier** [comment]
As the result of my researches, I think we need the next check-jobs:
1. bash syntax
2. shellcheck
3. travis-ci syntax
4. python (mb?)
Look forward to hear your opinion.

**Comment by esikachev** [comment]
@zemuvier what is the difference between 1 and 2 point? Travis automatically check syntax. python check will be useful when we will use python
